# åŸºæœ¬æ“ä½œå·¥ä½œæµç¨‹ã€‚

name: Trap_Wire_Inc.
on:
  # åœ¨ä¸»åˆ†æ”¯çš„æ¨é€ã€æ‹‰å–å’Œè¯·æ±‚äº‹ä»¶ä¸Šè§¦å‘å·¥ä½œæµã€‚
  push:
    branches: [ "https://github.com/TheProdigyLeague/srvSoft_DevOps/" ]
  pull_request:
    branches: [ "/home/qenmity/vulnScanner" ]

  # æ‰‹åŠ¨æ“ä½œå·¥ä½œæµç¨‹é€‰é¡¹å¡
  workflow_dispatch:
    inputs: {kernel}
    environments: 
        description: automated application deployment
        required: false
        default: staging
# é¡ºåºæˆ–å¹¶è¡Œè¿è¡Œä½œä¸šçš„å·¥ä½œæµç¨‹ã€‚
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: à¤¸à¥à¤•à¥à¤°à¤¿à¤ªà¥à¤Ÿ à¤šà¤²à¤¾à¤à¤
        run: echo '<!DOCTYPE html>';
      - name: à¤¬à¤¹à¥-à¤ªà¤‚à¤•à¥à¤¤à¤¿ à¤¸à¥à¤•à¥à¤°à¤¿à¤ªà¥à¤Ÿ
        run: | "Ereigniseingabeumgebung $
        {https://cinnamon-brass-76yh.squarespace.com/}" Â¤ (Â¯Â´â˜†âœ­.Â¸_)Â¤ ğ““á—´ğ“…á’ªÏŒâ“ Î²â„“ğ¨ğ“’ĞŒ Î­â“Å¤ğ”¯ï¼¹ Â¤(_Â¸.âœ­â˜†Â´Â¯) Â¤ "
 _____             __        ___          ___              
|_   _| __ __ _ _ _\ \      / (_)_ __ ___|_ _|_ __   ___   
  | || '__/ _` | '_ \ \ /\ / /| | '__/ _ \| || '_ \ / __|  
  | || | | (_| | |_) \ V  V / | | | |  __/| || | | | (__ _ 
  |_||_|  \__,_| .__/ \_/\_/  |_|_|  \___|___|_| |_|\___(_)
  |_|
# eof
